import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import CommonLayout from "@/components/client-view/common-layouts";
import connectToDB from "@/database";
import About from "@/models/About";
import Project from "@/models/Project";
import Achievement from "@/models/Achievement";
import Certification from "@/models/Certification";
import { Inter } from 'next/font/google';

async function extractAllData() {
  try {
    await connectToDB();
    const aboutData = await About.find({}).sort({ updatedAt: -1, createdAt: -1 }).limit(1);
    const projectData = await Project.find({});
    const achievementData = await Achievement.find({});
    const certificationData = await Certification.find({});

    return {
      about: aboutData && aboutData.length ? aboutData[0] : null,
      projects: projectData || [],
      achievements: achievementData || [],
      certifications: certificationData || []
    };
  } catch (error) {
    console.log(error);
    return {
      about: null,
      projects: [],
      achievements: [],
      certifications: []
    };
  }
}

const inter = Inter({ subsets: ["latin"] });
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "FullStack Portfolio Website",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const allData = await extractAllData();

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className} suppressHydrationWarning>
        <CommonLayout data={JSON.parse(JSON.stringify(allData))}>{children}</CommonLayout>
      </body>
    </html>
  );
}
